### ISSUE TITLE
This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions

### ISSUE THREAD

**Issue by rhawk301** [fwextensions/QuicKey#115]
(Disclosure: I am not a Chrome app Developer)

From: Chrome Web Store

Notice:
This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

QQ: Is there something the community can do to assist with this issue?

**Comment by fwextensions** [comment]
I've been working for awhile on a new version that supports the V3 extension manifest, which is what that warning in Chrome is complaining about.  It's been a slog, because the new version of the extension API changed a number of things that QuicKey depended on.  Hoping to release it very soon.

If you'd like to help and want to test the new version, here's the latest build: [QuicKey.zip](https://github.com/user-attachments/files/16647014/QuicKey.zip)

1. Download and unzip the QuicKey archive
2. Go to `chrome://extensions/` in the browser
3. Make sure *Developer mode* is toggled on in the top right of the page
4. Click *Load unpacked*
5. Navigate into the folder containing the unpacked QuicKey build
6. Click *Select folder* there

That should install the new version of QuicKey.  You can run both the production and test versions at the same time, but it may be a little confusing, so you can disable the production version while testing.  You'll want to add keyboard shortcuts to the new version, since they won't transfer from the production version.

Let me know if you see any issues, have questions, etc.  Thanks!

**Comment by fwextensions** [comment]
Version 2.0 is out now with support for manifest V3.
