### ISSUE TITLE
Previous / Next Tab Hotkey Behavior Option

### ISSUE THREAD

**Issue by KIDTREO** [fwextensions/QuicKey#116]
Great extension - nice work.  May I ask what determines the order Command A & S switches between Tabs with?  I expected switching to happen in the same order the tabs are listed in page, but instead find the "next / previous" tab selected jumps around?  Is there a way to set the behavior I expected?  

Thank you!

**Comment by fwextensions** [comment]
Those shortcuts switch the tabs in recency order, which is what you see in the QuicKey menu.  So you can jump right to the tab you were just on, rather than navigating through 8 adjacent tabs to get there.

There are built-in Chrome shortcuts for switching to the next/previous tab in their visible order: Command + Option + Left/Right arrow:

**Comment by fwextensions** [comment]
Please reopen if you are still seeing issues or have questions.
