### ISSUE TITLE
QuicKey pop-up opens on Alt-tab

### ISSUE THREAD

**Issue by ingemar-hn** [fwextensions/QuicKey#119]
Running Brave on Linux Mint. When I press alt-tab to switch to another window the QuicKey pop-up window appears just as if I had pressed alt-Q. Not a very big deal, but still slightly annoying. :)
Otherwise, a great plug-in!

**Comment by fwextensions** [comment]
I'm not familiar with how Mint does window management.  But if you mean the QuicKey popup window is treated like any other app window, then yes.  The popup stays open and "hides" behind the current Chrome window when it's dismissed, since there isn't support for completely hiding windows via the extension API.  But there are other options for hiding the window in the QuicKey Options page:

![image](https://github.com/user-attachments/assets/8d7d5227-8422-4d2c-b5e1-2215bae6e717)

Hiding the popup by moving it into the last tab in the window will keep it out of the alt-tab list, at the expense of the extra tab and slightly slower opening.

**Comment by ingemar-hn** [comment]
Right, thank you! That solved my issue. I actually saw that option but didn't fully understand the consequences.

**Comment by fwextensions** [comment]
Any thoughts you have on what might make that less confusing, let me know.  It's an awkward option to explain, as you have to compromise on something, no matter what you pick.

**Comment by ingemar-hn** [comment]
I can see your problem, it's hard to explain without being to wordy. Maybe you could just write as you did to me, that it's not possible to completely hide the window and that means that I as a user has to select the option that suites me best to keep the window out of sight.
