### ISSUE TITLE
Can't go forward if the "forward" tab was focused by QuicKey

### ISSUE THREAD

**Issue by garyking** [fwextensions/QuicKey#12]
If I use this ext to go to a tab, then use Ctrl-A to go back to the previous one, then when I hit Ctrl-S, nothing happens. 

This is only a problem when the "next" tab that Ctrl-S is supposed to focus on was previously focused by this extension.

**Comment by fwextensions** [comment]
Thanks for all the QA!  I think this may just be a confusingly named command, but that it's working correctly.  

As an example, let's say you open 5 tabs in order, so that tab E is the current one:

> A  B  C  D  **>E<**

Pressing <kbd>ctrl</kbd><kbd>A</kbd> once will switch back to tab D:

> A  B  C  **>D<**  E

Waiting a second and then pressing <kbd>ctrl</kbd><kbd>A</kbd> once will switch back to tab E:

> A  B  C  D  **>E<**

Now you want to get back to tab B, so you press <kbd>ctrl</kbd><kbd>A</kbd> three times *while the icon is inverted*, which moves you further back in the stack:

> A  **>B<**  C  D  E

But you realize you actually wanted tab C, so while the icon is inverted, you press <kbd>ctrl</kbd><kbd>S</kbd>:

> A  B  **>C<**  D  E

Now wait a second and press <kbd>ctrl</kbd><kbd>A</kbd> again when the icon is normal to switch to E, which was the most recently used tab before you started navigating:

> A  B  C  D  **>E<**

So <kbd>ctrl</kbd><kbd>S</kbd> is only really useful while navigating the stack.  Once the icon is back to normal, you'd just use <kbd>ctrl</kbd><kbd>A</kbd> to switch to the previous tab.  

Let me know if you have ideas on making that clearer.
