### ISSUE TITLE
Key Combination for "Switch to the previous tab" and "Switch instantly between the two most recent tabs" Not Working in Version 2.0.0

### ISSUE THREAD

**Issue by nzl-thu** [fwextensions/QuicKey#123]
In the previous version of QuicKey, I could press "Switch instantly between the two most recent tabs" twice and then "Switch to the previous tab," and it would work as expected:
![CleanShot 2024-10-01 at 11 19 25](https://github.com/user-attachments/assets/03aaaa18-a4b5-478b-b4a8-7859797fa6aa)

 However, this functionality seems to be broken in version 2.0.0:

![CleanShot 2024-10-01 at 11 21 43](https://github.com/user-attachments/assets/23144dfb-daa9-45ea-a0d0-2a5ddd540479)

Below are my keyboard shortcuts for quickey:
<img width="624" alt="CleanShot 2024-10-01 at 11 18 47@2x" src="https://github.com/user-attachments/assets/4e236ff6-d71e-45bb-ac43-53650d9590c2">

I really love this extension, but this issue has significantly affected my workflow. Could you please look into it? Thank you!

**Comment by dansteen** [comment]
I have a similar issue, but only when my most recent tab is a "web shortcut" (the kind that pretend to be a separate application on my system).   

This used to work pre 2.0.0 as well, but has been broken since in this particular circumstance.

**Comment by fwextensions** [comment]
@nzl-thu thanks for the clever use of Google image search in the GIF!  Just so I'm clear on the previous behavior in the first GIF:

* start on 2
* ctrl-Z to Extensions
* ctrl-Z to 2
* ctrl-A to 3

And to double-check, the ctrl-A works as expected in other situations, just not when doing it immediately after a ctrl-Z?  I had to remove ctrl-A and ctrl-S as default shortcuts because I didn't have enough (and they cause issues on macOS when the focus is on the location bar anyway).

@dansteen how are you setting a web shortcut and on which OS?  I just tried using *Cast, share, and save > Create shortcut...* on Windows, and it just creates a normal desktop shortcut that opens a regular tab.  If the shortcut is running in a separate window, are you able to find it if you search its name or URL in the QuicKey window and switch to it that way?

**Comment by nzl-thu** [comment]
> @nzl-thu thanks for the clever use of Google image search in the GIF! Just so I'm clear on the previous behavior in the first GIF:
> 
> * start on 2
> * ctrl-Z to Extensions
> * ctrl-Z to 2
> * ctrl-A to 3
> 
> And to double-check, the ctrl-A works as expected in other situations, just not when doing it immediately after a ctrl-Z? I had to remove ctrl-A and ctrl-S as default shortcuts because I didn't have enough (and they cause issues on macOS when the focus is on the location bar anyway).
> 
> @dansteen how are you setting a web shortcut and on which OS? I just tried using _Cast, share, and save > Create shortcut..._ on Windows, and it just creates a normal desktop shortcut that opens a regular tab. If the shortcut is running in a separate window, are you able to find it if you search its name or URL in the QuicKey window and switch to it that way?

@fwextensions Thanks for your reply! To make our discussion clearer, let’s define the actions as follows:

- **Action A (ctrl-A)**: "Switch to the previous tab"
- **Action B (ctrl-Z)**: "Switch instantly between the two most recent tabs"

Currently, in version 2.0.0, when performing the sequence: **Action B -> Action B -> Action A**, where each step is done immediately after the previous one, the final **Action A** fails. This behavior didn’t occur in earlier versions.

In other situations, **Action A** works as expected. This issue seems unrelated to the specific key bindings, so you may try binding a different shortcut to reproduce the issue :)

**Comment by fwextensions** [comment]
@nzl-thu, hopefully the 2.0.1 version that just got published will fix the navigation issue you found.

**Comment by nzl-thu** [comment]
> @nzl-thu, hopefully the 2.0.1 version that just got published will fix the navigation issue you found.

@fwextensions, Thank you so much for your effort on resolving my issue!

The key sequence **Action B -> Action B -> Action A** now works without causing the final Action A to fail, which is great. However, it seems that the new behavior is still a bit different from the previous version. Specifically:

For example, with three tabs **Tab 1, Tab 2, Tab 3** (sorted by most recently used order), and currently on **Tab 1**:

- In the previous version, the **Action B -> Action B -> Action A** sequence would yield: **Tab 1 -> Tab 2 -> Tab 1 -> Tab 3**.
- In the new version, the same sequence yields: **Tab 1 -> Tab 2 -> Tab 1 -> Tab 2**.

I understand this might be a tricky edge case (yet important for my workflow) and I really appreciate all the time and effort you've already put into fixing this. If there's anything else I can provide to help clearify this further, please let me know. Thanks again for your work!

**Comment by nzl-thu** [comment]
> > @nzl-thu, hopefully the 2.0.1 version that just got published will fix the navigation issue you found.
> 
> @fwextensions, Thank you so much for your effort on resolving my issue!
> 
> The key sequence **Action B -> Action B -> Action A** now works without causing the final Action A to fail, which is great. However, it seems that the new behavior is still a bit different from the previous version. Specifically:
> 
> For example, with three tabs **Tab 1, Tab 2, Tab 3** (sorted by most recently used order), and currently on **Tab 1**:
> 
> * In the previous version, the **Action B -> Action B -> Action A** sequence would yield: **Tab 1 -> Tab 2 -> Tab 1 -> Tab 3**.
> * In the new version, the same sequence yields: **Tab 1 -> Tab 2 -> Tab 1 -> Tab 2**.
> 
> I understand this might be a tricky edge case (yet important for my workflow) and I really appreciate all the time and effort you've already put into fixing this. If there's anything else I can provide to help clearify this further, please let me know. Thanks again for your work!

The reason this specific behavior is important for me is that, when I'm on **Tab 1**, I might want to switch to a recently used tab. To do this, I often inspect whether the most recent tab is the one I need (by performing **Action B**, which takes me to **Tab 2**). If it's not the one I want, I then switch back to **Tab 1** before accessing the *next* item in the Most Recently Used (MRU) list, which in this case would be **Tab 3** (the one following **Tab 2**).

In the previous version, the **Action B -> Action B -> Action A** sequence allowed me to quickly follow this logic, resulting in **Tab 1 -> Tab 2 -> Tab 1 -> Tab 3**.

**Comment by fwextensions** [comment]
Thanks for the detailed response!  Very helpful for understanding what you're looking to achieve.

Here's an example that will hopefully make things clearer.  Assume a window with 6 tabs in the least recent to most recent order of `4 6 5 3 2 1`.  The `[toggle]` command is your action B, which toggles instantly between the two most recent tabs.  The `[back]` command is your action A, which goes back to the previous tab and starts a cooldown timer.  If you press it again within 750ms, it'll push farther back in the recent stack.  So there's basically a pointer that moves down the stack with each `[back]` command, and then resets after the cooldown ends.

This is an example of pressing `[toggle]` twice and then `[back]` twice within 750ms, and then waiting for the cooldown to end:

```
recents:  4  6  5  3  2  1
pointer:                 ^

[toggle]
          4  6  5  3  1  2
                         ^
[toggle]
          4  6  5  3  2  1
                         ^
[back]
          4  6  5  3  2  1
                      ^
[back]
          4  6  5  3  2  1
                   ^
[wait 750ms]
          4  6  5  2  1  3
                         ^
```

Hopefully that shows why `toggle > toggle` should always produce the same outcome as `toggle > back`.  I think there was a timing bug in the previous version that would cause the pointer to be in the wrong place after a quick toggle, so the next `[back]` command would start too far down the stack.  I don't want to mess with your muscle memory, but I'm not sure there's a way to avoid the additional press of `ctrl-A` to get from tab 1 to tab 3.

One thing I've been thinking about is having an option for the "Switch to previous tab" command that would limit it to the 3 or 4 most recent tabs.  That way, if you pressed it one too many times, you could just keep hitting it until it wrapped around to the tab you wanted, rather than having to switch to a different shortcut to go back in the other direction.  Hopefully it would feel more like the toggle command, where you could freely spam it.  Does that sound useful?

**Comment by nzl-thu** [comment]
> Thanks for the detailed response! Very helpful for understanding what you're looking to achieve.
> 
> Here's an example that will hopefully make things clearer. Assume a window with 6 tabs in the least recent to most recent order of `4 6 5 3 2 1`. The `[toggle]` command is your action B, which toggles instantly between the two most recent tabs. The `[back]` command is your action A, which goes back to the previous tab and starts a cooldown timer. If you press it again within 750ms, it'll push farther back in the recent stack. So there's basically a pointer that moves down the stack with each `[back]` command, and then resets after the cooldown ends.
> 
> This is an example of pressing `[toggle]` twice and then `[back]` twice within 750ms, and then waiting for the cooldown to end:
> 
> ```
> recents:  4  6  5  3  2  1
> pointer:                 ^
> 
> [toggle]
>           4  6  5  3  1  2
>                          ^
> [toggle]
>           4  6  5  3  2  1
>                          ^
> [back]
>           4  6  5  3  2  1
>                       ^
> [back]
>           4  6  5  3  2  1
>                    ^
> [wait 750ms]
>           4  6  5  2  1  3
>                          ^
> ```
> 
> Hopefully that shows why `toggle > toggle` should always produce the same outcome as `toggle > back`. I think there was a timing bug in the previous version that would cause the pointer to be in the wrong place after a quick toggle, so the next `[back]` command would start too far down the stack. I don't want to mess with your muscle memory, but I'm not sure there's a way to avoid the additional press of `ctrl-A` to get from tab 1 to tab 3.
> 
> One thing I've been thinking about is having an option for the "Switch to previous tab" command that would limit it to the 3 or 4 most recent tabs. That way, if you pressed it one too many times, you could just keep hitting it until it wrapped around to the tab you wanted, rather than having to switch to a different shortcut to go back in the other direction. Hopefully it would feel more like the toggle command, where you could freely spam it. Does that sound useful?

@fwextensions, thank you so much for your thoughtful response! I appreciate the idea of adding an option to limit the recent tabs in `[back]` to the 3 or 4 most recent ones—it’s a helpful enhancement. However, I still feel that my main concern remains.

I fully understand the current logic of this extension, but I also believe the previous `[toggle]` logic had advantages that could improve overall user convenience. If possible, would you consider adding an option (disabled by default so being compatible with the current logic) to restore the earlier toggle behavior? This would allow users to navigate tabs like this:

```
recents:  4  6  5  3  2  1
pointer:                 ^

[toggle]
          4  6  5  3  1  2  (toggling 2, but finding it isn’t the expected tab)
                         ^
[toggle]
          4  6  5  3  2  1  (restoring the previous order)
                         ^
[back]
          4  6  5  2  1  3  (jumping directly to tab 3 to check if it’s the right one)
                         ^
```

I genuinely believe this option could be valuable for users who frequently inspect and switch between tabs, helping them navigate more efficiently and with fewer missteps.

Thank you again for your time and consideration! I truly appreciate the work you’re doing and look forward to your thoughts.
