### ISSUE TITLE
Is there a way to cycle between two most recent tabs?

### ISSUE THREAD

**Issue by avalanche1** [fwextensions/QuicKey#17]
E.g. I'm on google.com. And the previous tab I've visited is github.com. And I have lots of other open tabs.
What I'd like to have is a kb shortcut to cycle bw google and github tabs.
There's something similar when I double-press alt-q - but it works haphazardly.
Can we make a special function for this? Or stabilize the current shortcut

**Comment by fwextensions** [comment]
You can press alt-A, wait .75 seconds until the icon changes back to normal, and then press it again to switch back to the previous tab.  It sounds like you'd want a shortcut that can be pressed more rapidly, though.  

Funnily enough, I have an alt-Z toggle shortcut on a branch that lets you press it as quickly as you want and it will only switch between the two most recent tabs: https://github.com/fwextensions/QuicKey/tree/feature/toggle-shortcut

Which OS are you on where you see the alt-Q double-press be unreliable?  I think there's a bug in Chrome that very occasionally causes it to not close the open menu when you press the shortcut again, and the extension relies on that to detect the double-press.  Also, if you have lots of tabs that are actively doing things, double-pressing too quickly can cause it not to work because the extension doesn't have enough time to detect the two presses.

**Comment by avalanche1** [comment]
Actually, I'd want a shortcut that is only needed to be pressed once.
I had a similar extension installed but it was buggy. https://chrome.google.com/webstore/detail/toggle-tabs/amlniobkkcncmkejklnnhkbjkmhfjmla

**Comment by fwextensions** [comment]
Right, I've added a new shortcut on [this branch](https://github.com/fwextensions/QuicKey/tree/feature/toggle-shortcut) that you can press as quickly as you want to switch between the two most recent tabs.

**Comment by fwextensions** [comment]
A keyboard shortcut for toggling between the two most recent tabs without a delay is now available in v1.2.0.

**Comment by avalanche1** [comment]
perfext!
