### ISSUE TITLE
QuicKey doesn't seem to forget some closed tabs

### ISSUE THREAD

**Issue by dharber** [fwextensions/QuicKey#2]
I'm generally loving QuicKey but I've stumbled across a weird glitch. I had a dozen or so tabs open to various parts of a website. If I typed in the common string they all had, most of them would have an 'x' on the right side allowing me to close them. Some others, however, wouldn't have the 'x' on the right side. There was an 'x' on the _left_ side but clicking on that just went to the tab.

If I try to close that tab, it still shows up in QuicKey when I type the string the tab would still be listed and clicking on it would _reopen_ the tab that I had already closed.

One thing all of these phantom tabs seem to have in common is they were suspended by Tab Suspender. But I don't think all of the suspended tabs had this problem (although at this point I can't swear to that because all of the closeable tabs are closed.)

I appear to be using version 1.0.2 of QuicKey.

EDIT:
Also, I tried unsuspending the tabs and then closing them but the result was the same. The tabs still show up in QuicKey and it still reopens them if I try to click on them.

**Comment by fwextensions** [comment]
Thanks for the feedback!  It sounds like you're seeing expected behavior, where the 25 most recently closed tabs are shown at the bottom of the recent tabs list, and which will also match the typed query (though their match scores are discounted, so they should be lower in the results).  If you've closed some tabs from a site, and then type the name of the site, the closed tabs should show up.

Closed tabs are rendered with grey text and an X icon on the left:

![image](https://user-images.githubusercontent.com/61631/56003590-ff91f880-5c7b-11e9-8082-d1784c32a431.png)

That said, this behavior may not be entirely clear, and using the same icon as the close button probably wasn't a great idea.  Maybe using a strikethrough style on the tab title and URL would be better?  

![image](https://user-images.githubusercontent.com/61631/56003725-c443f980-5c7c-11e9-9f08-1c2f8f15d77d.png)

I'm working on an update that adds some options, like customizing the keyboard shortcuts and changing the behavior of the spacebar.  I should maybe add an option to not include recently closed tabs in the results.

**Comment by dharber** [comment]
Thanks for the response. I believe you are correct that it was showing recently closed tabs. Since I didn't realize QuicKey actually did that, I didn't know what I was looking at.

That said, I will note that I have occasions, in retrospect, where I have closed so many related tabs at once that QuicKey would only display closed tabs at the top of the results list which was not helpful at all. I guess that while it seems like a nice feature, I would prefer to be able to disable it for the vast majority of my use cases.

**Comment by fwextensions** [comment]
I'm planning on adding an option to not show closed tabs to the next update.  I've also changed the icon to something more like a history icon, so at least it won't be confused with the close button.

**Comment by fwextensions** [comment]
The latest [v1.1.0](https://chrome.google.com/webstore/detail/quickey-%E2%80%93-the-quick-tab-s/ldlghkoiihaelfnggonhjnfiabmaficg?authuser=2) release adds the option to not show closed tabs in the search results.  Right-click the QuicKey icon, select *Options*, then uncheck the *Include recently closed tabs in the search results* option.
