### ISSUE TITLE
Indicate if the tab is not in the current window

### ISSUE THREAD

**Issue by garyking** [fwextensions/QuicKey#20]
By default, when searching for a tab, I assume that it's in the current window. If a tab in the search results is not in the current window, then please indicate it as such somehow, by prepending it with an icon, or dim the row or something.

Because I group my tabs in windows by how related they are, so this would be quite useful.

**Comment by fwextensions** [comment]
I've added an icon for tabs in other windows on a [branch](https://github.com/fwextensions/QuicKey/tree/feature/other-window-icon).  Tabs in the same window don't have an icon, so that users who only have one window don't see extra noise.  

The incognito icon takes precedence, so if you have multiple incognito windows, you wouldn't be able to tell which tabs are in the current window.  But that seems like a less common use case.

I think I'd also add an option to toggle the icons off.

![image](https://user-images.githubusercontent.com/61631/68078462-1c665880-fd93-11e9-8f7a-fa5192f2c1f3.png)

**Comment by fwextensions** [comment]
This is now available in v1.3.0.  It's off by default if you have more than 4 windows open, but you can always turn it on in options.
