### ISSUE TITLE
[Feature Request] Show badge tab count

### ISSUE THREAD

**Issue by KlausDevWalker** [fwextensions/QuicKey#24]
It would be nice if we could see the montitude of open tabs I leave on my Vivaldi hahaha BTW, your extension is marvelous. Thanks for sharing with us :)

**Comment by fwextensions** [comment]
Thanks for the feedback!

You mean, you want a badge on the QuicKey icon to show the total number of open tabs?

**Comment by KlausDevWalker** [comment]
That's it :) Now that I noticed that I didn't my request clear. Sorry ^_^'

**Comment by fwextensions** [comment]
I've got this working on a [branch](https://github.com/fwextensions/QuicKey/tree/feature/show-tab-count).  Any feedback on the badge color?  

Below is what it looks like by default, and then it changes to the default Chrome blue when you switch tabs, instead of inverting the whole icon (since half of the icon is hidden by the badge):

![image](https://user-images.githubusercontent.com/61631/71936883-8b7b7700-315f-11ea-8c64-2c4d80202d74.png)  ![image](https://user-images.githubusercontent.com/61631/71936914-a0f0a100-315f-11ea-90e1-72d3f60c2fb8.png)

**Comment by KlausDevWalker** [comment]
Neat and nice! But if you don't want to "lose" your work on the current icon you could make something like a caption (anything similar to my terrible mockup ^_^') 
![image](https://user-images.githubusercontent.com/3390598/72038460-384d1580-3280-11ea-9afa-4c8368cdb1c1.png)

Thanks again :)

**Comment by fwextensions** [comment]
The extension doesn't have any control over where Chrome draws the badge, so showing any badge will cover the bottom part of the icon.  It'll be an option that users can turn on or off, so I'm not too concerned about the icon.  It's more what colors to use, and how to indicate to the user whether pressing the previous tab keyboard shortcut again will navigate further back in the stack or will toggle back to the most recent tab.

**Comment by fwextensions** [comment]
This option has been added to v1.4.0.
