### ISSUE TITLE
Distracting color change when switching between windows

### ISSUE THREAD

**Issue by ubershmekel** [fwextensions/QuicKey#26]
I sometimes have multiple Chrome windows open on one screen. When I switch between them, the `Q` logo for the extension goes from black to grey and back to black. It's a bit distracting and it's the only extension that does that. Is there a way to make it stop doing that?

**Comment by fwextensions** [comment]
I wrote this in response to a question posted in the Chrome store about why the icon inverts (it's a gist because the Chrome forums are terrible and don't even support multiple paragraphs): https://gist.github.com/fwextensions/f2a79df5530354d6ef3058d3671c427a

Basically, it's so when you're navigating back in the stack of recent tabs using the keyboard shortcut, you know if you can press it again to go further back, or whether pressing it will switch back to the tab you started from.  It's a workaround for the limitation in Chrome that an extension doesn't know when the modifier keys are released for its keyboard shortcut, so it can't provide exactly the same behavior you get with <kbd>alt</kbd><kbd>tab</kbd>.  (At least one other tab switching extensions does a similar thing.)

The last paragraph of that gist is probably most relevant to your question:

> Actually, it just occurred to maybe you're asking about why the icon inverts when you use some *other* way of switching tabs, like pressing <kbd>ctrl</kbd><kbd>tab</kbd> repeatedly to move between tabs in order.  It's for a related reason: if you keep navigating while the icon is inverted, those intermediate tabs are not counted as "recently used".  So if you then wait for the icon to switch back to normal, pressing <kbd>alt</kbd><kbd>A</kbd> will switch back to where you started, rather than the tab to the left of where you ended up.

But since a few people have commented on it, it might be worth revisiting.  If I limited it to when you're navigating via the shortcut, it wouldn't surprise people who are switching tabs some other way, like just switching between windows.  You'd lose support for the scenario above, but that's a bit of a narrow case.  (Hmm, I'd also have to rethink how the icon gets switched when going into dark mode...)

**Comment by fwextensions** [comment]
The latest 1.4.0 version changes the icon inversion behavior.  It will only invert when you've just used the switch to previous/next tab shortcut, since that's when you need to know whether the pressing it again will navigate further into the stack or switch back to where you started.  Changing the active tab by other means, like pressing <kbd>alt</kbd><kbd>tab</kbd>, doesn't invert the icon.
