### ISSUE TITLE
Windows - Navigating tab list by pressing Q multiple times while holding Alt button

### ISSUE THREAD

**Issue by farukozsoy** [fwextensions/QuicKey#3]
Hi,

Would it be good if we could navigate through the recent tabs list by pressing Q multiple times while holding Alt button? I am aware that quick double pressing Q switches the most recent tab, but navigating tab list by pressing Q multiple times (a bit slower), like Alt+Tab in windows, would improve user experience and removes the need to use the arrow keys, I think.

Regards, and thanks for the really nice extension

**Comment by fwextensions** [comment]
Thanks for the feedback!  I totally agree that using <kbd>alt</kbd>+<kbd>Q</kbd> to navigate the list would be better, and that was my original plan.  But it turns out that Chrome automatically closes the popup menu when you press the same command that was used to initially open it.  The extension doesn't get a chance to intercept that event at all.  After discovering that, I added the double-press so you could at least do something useful without switching you hand to different keys.  

Also, did you know you can use the <kbd>W</kbd> key to move the selection down the list while holding <kbd>alt</kbd>?  When you release <kbd>alt</kbd>, QuicKey will switch to the selected tab.  Not as nice as using <kbd>Q</kbd>, but only one key over.  That was as close as I could get to emulating the <kbd>alt</kbd>+<kbd>tab</kbd> experience without any additional software:

![gif](https://fwextensions.github.io/QuicKey/img/mru-menu.gif)

However, since you're on Windows, you could install AutoHotkey and run a script I've created that will intercept <kbd>ctrl</kbd>+<kbd>tab</kbd> and let you press it once to toggle between the recent tabs, or keep holding <kbd>ctrl</kbd> and then use <kbd>tab</kbd> to navigate the list.  [This page](https://fwextensions.github.io/QuicKey/ctrl-tab/) describes how to set it up.

**Comment by farukozsoy** [comment]
Thanks for clarification.

For me using W key after Alt+Q is a fair enough workaround for the situation, I adapted to it already.

Thanks again.
