### ISSUE TITLE
Tabs with malformed URLs can trigger an uncaught exception on browser restart

### ISSUE THREAD

**Issue by avalanche1** [fwextensions/QuicKey#43]
After re-opening chrome with 400+ tabs the extn stopped working.
It shows 0 tabs instead of 400 on the badge.
When I open new tab, the counter increases from 0 to 1 - but when I click the badge, the tab list is empty, search shows nothing.
None of the kb shortcuts work.
Options page is blank; with an error in the console (although, since it's minified, it's useless):
```
base.js:24 URIError: URI malformed
    at decodeURI (<anonymous>)
    at base.js:24
```

I tried turning on\off, uninstall-close_chrome-install, clearing chrome.storage.local - nothing helps.

From recent changes that I did were enabling tf options in The Great Suspender:
- Never suspend tabs when offline
- Apply Chrome's built-in memory-saving when suspending 
- Instantly suspend when system memory gets very low  
- Automatic deactivation of any kind of tracking

Maybe, the last option breaks smth, if you've got GA tracking. But unchecking those options didn't help.

**Comment by fwextensions** [comment]
Thanks for letting me know.  The number of tabs shouldn't matter.  I regularly have 500 - 700 tabs open.  I also don't think The Great Suspender options are affecting QuicKey.

It looks like you've got a tab open with a malformed URL, and I'm not correctly handling the exception that can happen in that case when the extension loads after a restart.  Since you're familiar with the Chrome console, can you run the following code from the console in the options page or the background page?  

    chrome.tabs.query({}, tabs => tabs.map(({url}) => { try { decodeURI(url) } catch (e) { console.log(url, e) } }))

That should spit out the URL (or URLs) that are causing the exception.  Can you let me know what the URL is?  

If you close that tab and then quit and reopen Chrome, QuicKey should load fine.  You could also go to the Extensions page and then disable and re-enable QuicKey to force it to reload after the tab is closed.

**Comment by avalanche1** [comment]
I also happen to be chrome extn dev - so I can help you debug it thouroughly

**Comment by avalanche1** [comment]
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=%D0%9F%D1%80%D0%BE%20%D0%BA%D0%BE%D1%80%D0%BE%D0%BD%D0%B0%D0%B2%D0%B8%D1%80%D1%83%D1%81.%20-%20%D0%A4%D0%BE%D1%80%D1%83%D0%BC%20%C2%AB%D0%9B%D0%B5%D1%87%D0%B5%D0%B1%D0%BD%D0%BE%D0%B5%20%D0%B3%D0%BE%D0%BB%D0%BE%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%C2%BB&pos=0&uri=http://golodanie.su/forum/showthread.php?t=23539&highlight=%EA%EE%F0%EE%ED%E0%E2%E8%F0%F3%F1

`klbibkeccnjlkjkiokjodocebajanakg` extn is The Great Suspender 7.1.8

**Comment by avalanche1** [comment]
Your advice helped. thanks a lot!
Your extn is way better than the rest - I felt w\o it like w\o hands!

**Comment by fwextensions** [comment]
Thanks very much for the debugging help!  Glad you're finding QuicKey useful.

I'm reopening this, as it's a legit bug that I need to fix.  Opening a page with a malformed URL shouldn't completely break QuicKey.

**Comment by avalanche1** [comment]
How can I donate to the cause?
