### ISSUE TITLE
Search algorithm

### ISSUE THREAD

**Issue by avalanche1** [fwextensions/QuicKey#44]
I think fuzzy search works incorrectly. Dunno, if it's inherent to the algo itself, or the implementation.
![image](https://user-images.githubusercontent.com/10534563/100856589-b029bd00-349c-11eb-9d90-138f991f6042.png)
IMO it should be sorted in tf order: 3-4-2-1

![image](https://user-images.githubusercontent.com/10534563/100856756-e23b1f00-349c-11eb-897b-e79ecc32bf9a.png)
this one: 3-2-1-4

**Comment by fwextensions** [comment]
QuicKey adds a 15% boost for tabs accessed in the last 5 seconds, and then a scaled boost up to 10% for tabs accessed over the last 3 days.  There are also penalties for longer names and URLs, since the longer the string, the more likely there is to be a match with a short query,  The goal is to require as few key presses as possible to get to the most likely result, but the algorithm certainly isn't perfect.

You can compare the algorithm QuicKey uses, minus the recency boost, here: https://fwextensions.github.io/quick-score-demo/

**Comment by avalanche1** [comment]
I would drop the 1st boost. tabs accessed in last 5s are visible in the list as as - a couple of space bars and you're on the tab you want.

**Comment by fwextensions** [comment]
That 15% boost is actually from way back before the extension even showed recent tabs.  It started out as just a way of searching through the open tabs, so you'd have to type at least a character or two to get to a recently visited tab.
