### ISSUE TITLE
chrome address bar Command + a to select all acting as Ctrl + a acts as switch to previous tab

### ISSUE THREAD

**Issue by krishna81m** [fwextensions/QuicKey#49]
Here I got to second tab and press Command + a to select text but it switches to first tab.

![command+a+on+statusbar+switches](https://user-images.githubusercontent.com/2347180/107841855-b3320b00-6d73-11eb-8df7-4ebdcd0abd63.gif)

**Comment by fwextensions** [comment]
This is due to a [known bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1032712) in Chrome (and MS Edge) on macOS, as described in #35.   There's no way to workaround it, other than to change the shortcut to something that isn't used in the Windows Edit menu.

Closing this to consolidate the discussion on the earlier issue.

**Comment by krishna81m** [comment]
Command + L is my new friend to also select the URL.

**Comment by fwextensions** [comment]
Yup, that's what I use to focus the location bar.

Keep in mind that you can change the default ctrl-A keyboard shortcut to something else to avoid the Chrome bug, or just clear it if you're not using that command.

**Comment by NN---** [comment]
Maybe change defaults to Ctrl+Q, Ctrl+W  instead of Ctrl+A, Ctrl+S so this doesn't hit users ?
