### ISSUE TITLE
[Feature Request] customize theme

### ISSUE THREAD

**Issue by kevinhwang91** [fwextensions/QuicKey#83]
Great to see this extension support Chinese pinyin that I found it's unique for the related extensions.
~~Have you used a fuzzy finder like [fzf](https://github.com/junegunn/fzf)? I think it's so popular and can use `<ctrl-j>`/`<ctrl-k>` to select the items. I hope QuickKey can add options to customize the shortcuts. Look like chrome has occupied the shortcuts I mention, if it's hard for the extensions to remap `<ctrl-j>`/`<ctrl-k>` , `<tab>`/`<S-tab>` is acceptable.~~
2. Add css style or provide a dark theme, I'm using gnome, looks like the dark mode doesn't work.

**Comment by kevinhwang91** [comment]
`google-chrome-stable --enable-features=WebUIDarkMode --force-dark-mode` as a workround.

**Comment by fwextensions** [comment]
Yes, QuicKey uses the [quick-score](https://www.npmjs.com/package/quick-score) library for fuzzy matching, including for pinyin searches.  I'm curious how the fuzzy pinyin works for you.

Looks like you found that the `ctrl-j/k` shortcuts move the selection up and down the list of tabs? 

Re: the dark mode, it does automatically switch to dark mode based on the system settings in macOS and Windows.  #45 was opened awhile ago regarding dark mode on Gnome, and it sounds like the auto-switching still hasn't been implemented there.  The issue seems to be that Chrome on Gnome isn't reporting the "prefers dark mode" setting to CSS media queries correctly, so there's no way to automatically switch.  Have you seen any Chrome extensions auto switch on Gnome?

**Comment by kevinhwang91** [comment]
> Yes, QuicKey uses the [quick-score](https://www.npmjs.com/package/quick-score) library for fuzzy matching, including for pinyin searches. I'm curious how the fuzzy pinyin works for you.

Work fine for me. It's extremely useful for Chinese users. I have just used it for several hours.

> Looks like you found that the `ctrl-j/k` shortcuts move the selection up and down the list of tabs?

Yes, my bad. I didn't read the readme carefully.

> Re: the dark mode, it does automatically switch to dark mode based on the system settings in macOS and Windows. #45 was opened awhile ago regarding dark mode on Gnome, and it sounds like the auto-switching still hasn't been implemented there. The issue seems to be that Chrome on Gnome isn't reporting the "prefers dark mode" setting to CSS media queries correctly, so there's no way to automatically switch. Have you seen any Chrome extensions auto switch on Gnome?

The issue has existed for a long time, `--force-dark-mode` is buggy sometimes, I hope QuickKey can provide an option for Linux users.
