### ISSUE TITLE
Featured badge

### ISSUE THREAD

**Issue by memeplex** [fwextensions/QuicKey#86]
Hi, why does your extension not sport the featured badge as described in:

https://support.google.com/chrome_webstore/answer/1050673?authuser=0#zippy=%2Cunderstand-chrome-web-store-badges

https://developer.chrome.com/docs/webstore/discovery/#badges

Sorry for asking these questions but I would like to use the extension and want to be sure it's as secure as possible.

**Comment by fwextensions** [comment]
No problem.  You can't be too careful these days, as there are plenty of sketchy extensions out there.

QuicKey does show the "Established Publisher" badge:

![image](https://user-images.githubusercontent.com/61631/196306675-3adfb5d5-df15-49e2-af23-95253edee4f8.png)

I think it doesn't show the Featured badge yet just because it's still using [V2 of the manifest format](https://developer.chrome.com/docs/webstore/best_practices/):

> Manifest V3: Is the extension built on Manifest V3? Manifest V3 is the current version of the Chrome extension platform and all High Quality extensions should use it. (See the [Manifest V3 overview](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/).)

V2 extensions will continue to work through the end of next year, though Google might "experiment" with turning them off in the stable channel mid year.  Migrating to V3 is on my todo list, but it's a bit of a hassle, as they're doing away with background pages in favor of service workers.  I'm planning on working on it over the next couple months.

**Comment by memeplex** [comment]
I see, it makes sense. Thanks for taking the time to explain it!

**Comment by fwextensions** [comment]
FWIW, the latest 1.8.1 upload now has the Featured badge:

![image](https://github.com/fwextensions/QuicKey/assets/61631/5a49ac0c-a1b1-4a48-90da-bd2074d7f6ae)

It's still using manifest V2.  Maybe since Google pushed out the V3 transition, that's no longer a requirement to get the badge.

**Comment by AungThuSoe24** [comment]
Don't use this link same account is
Another person my account hacking 
Now help me please this link unlink
Do it
